var userInfo = [{
        userName: "Pam Beesly",
        password: "<<L5EVys4LFe[9}C",
        account: false,
        email: "pam@gmail.com",
        profilePicture: "",
    },
    {
        userName: "Jim Helpert",
        password: "YB66>>s_?jwG$L",
        account: true,
        email: "jim@gmail.com",
        profilePicture: "",
    },
    {
        userName: "Michael Scott",
        password: "password",
        account: false,
        email: "mich@gmail.com",
        profilePicture: "",
    },
    {
        userName: "Toby Flenderson",
        password: ">jUDQADv7{U$veHS",
        account: true,
        email: "toby@gmail.com",
        profilePicture: "",
    },
    {
        userName: "Dwight Schrute",
        password: "Uc^X;Q<}rm.6Q6qG",
        account: true,
        email: "d.s@gmail.com",
        profilePicture: "",
    }, {
        userName: "Quintin",
        password: "qazxsw",
        account: false,
        email: "quintin.vos@gmail.com",
        profilePicture: "",
    }, {
        userName: "Tesh Book",
        password: "12345",
        account: true,
        email: "tesh.book@gmail.com",
        profilePicture: "",
    }, {
        username: "Mai",
        password: "oqPIr52jm1q6",
        account: false,
        email: "mai@gmail.com",
        profilePicture: "",
    }, {
        username: "Nina",
        password: "Nina",
        account: true,
        email: "nina.havenga@gmail.com",
        profilePicture: "",
    }, {
        username: "Kingslayer420",
        password: "oqPIr52jm1q6",
        account: true,
        email: "dylan@gmail.com",
        profilePicture: "",
    }, {
        username: "Sleep",
        password: "Let1t5leep",
        account: true,
        email: "alex.andris@gmail.com",
        profilePicture: "",
    }, {
        username: "TheBlack",
        password: "oqPIr52jm1q6",
        account: false,
        email: "micheal.root@gmail.com",
        profilePicture: "",
    }, {
        username: "Alexandria",
        password: "SeeWhat'sontheInside",
        account: true,
        email: "christain@gmail.com",
        profilePicture: "",
    }, {
        username: "NoName2012",
        password: "Lboise12",
        account: true,
        email: "louis@gmail.com",
        profilePicture: "",
    }
]